version: 0.2

env:
  parameter-store:
    IMAGE_REPO_NAME: /app/ecr-creds/IMAGE_REPO_NAME
    IMAGE_TAG: /app/docker-creds/image-tag
    AWS_ACCOUNT_ID: /app/docker-creds/account-id
    AWS_REGION: /app/ecr-creds/region
    DOCKER_REGISTRY_URL: /app/docker-creds/docker-registry
    DOCKER_USERNAME: /app/docker-creds/docker-username
    DOCKER_PASS: /app/docker-creds/docker-pass

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm install
      - echo "Logging in to Docker Registry"
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - echo "Logging in to Amazon ECR"
      - ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_URI"

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "$IMAGE_REPO_NAME:$IMAGE_TAG" .
      - docker tag "$IMAGE_REPO_NAME:$IMAGE_TAG" "$ECR_URI:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push "$ECR_URI:$IMAGE_TAG"
      - echo "Writing imagedefinitions.json"
      - printf '[{"name":"node-app","imageUri":"%s"}]' "$ECR_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
